### ISSUE TITLE
bin/climaf error when CLIMAF_CACHE dir does not exist

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#130]
I have by mistake set CLIMAF_CACHE to a non existing directory and then launched bin/climaf just to see what happened, and then exited right away. I got a _Issue when writing cache index_ error

```
In [2]:
Do you really want to exit ([y]/n)? y
error    : Issue when writing cache index /data/jypmce/climafcache/index

(cdatm-nightly_py2) [jypmce@ciclad-ng ~]$ ls /data/jypmce/climafcache
ls: cannot access /data/jypmce/climafcache: No such file or directory
```
The error makes sense, because the cache directory does not exist, but I think that either the error message should be more explicit (e.g. _Cache directory does not exist and can't be updated_) or the cache directory should be created on the fly.

Does the user need to explicitly create the cache directory, or is it created automatically at some point?

**Comment by jservonnat** [comment]
@jypeter normally CliMAF creates the cache when it doesn't exist. 
The error message should actually be a warning message.

**Comment by jservonnat** [comment]
@rigoudyg we will try to include more infos on the duration of a CliMAF session and potentially on the complete exectution of a cfile command. Let's talk about this tomorrow at the bocal!

**Comment by jservonnat** [comment]
@jypyter I've modified the behavior of the error message. If your cache doesn't exist but you have nothing to put in it, then you have no error message.
If the cache index file exists and you have something to add to it, and can't, then you have an error.
