### ISSUE TITLE
Notes about the "Installing, configuring, using" page

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#132]
I have noticed two minor inconsistencies in the [Installing, configuring, using](https://climaf.readthedocs.io/en/latest/installing.html#installing-configuring-using) page

The _Using CliMAF at CNRM, on Ciclad or Climserv: fast track_ section
- says that on ciclad/climserv you initialize with `module load climaf` which seems indeed to load several modules and initializes a python. But the _Configuring CliMAF_ section says that on ciclad you have to `module load python` and `module load ncl/6.3.0`. These 2 module load are not required (any more).
- mentions a `CLIMAF `variable (`point to a CliMAF install ($CLIMAF environment variable)`), but the _Configuring CliMAF_ section does not mention this CLIMAF variable (and what it is for)

**Comment by jservonnat** [comment]
Done
