### ISSUE TITLE
Missing optional requirements

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#133]
When running `./test_install.sh` at LSCE, I get the following
```
which: no epstopdf in (very long list)
error    : 'defining cepscrop : command epstopdf is not executable'
warning  : Binary cdftools not found. Some operators won't work
```
These seem to be warnings and I can probably survive without what's missing, but the missing dependencies (and what they are for) should maybe be listed after `ncview` in https://climaf.readthedocs.io/en/latest/requirements.html#requirements

**Comment by jservonnat** [comment]
@rigoudyg it is related with the issue you mentioned (i.e. need to find an alternative to epstopdf)

**Comment by jservonnat** [comment]
I've added epstopdf at the list of requirements.
