### ISSUE TITLE
TWO CM_atlas related problems

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#134]
_[Don't know if this is an issue, or just a temporary side effect of `/bdd` not being accessible on ciclad today]_

I'm trying to understand/reproduce what is detailed in the `Gathering_my_results_in_an_html_page` notebook but

### Using "module load climaf" on ciclad

If I use the settings defined by @jservonnat , the CM_atlas module is not defined
```
>>> from CM_atlas import *
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: No module named CM_atlas
```
```
$ echo $PYTHONPATH
/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_1.2.10
-bash-4.1$ find /ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_1.2.10 -name CM_atlas
$
```

### Using my version of climaf
If I use my own environment ("CDAT 8.1 based python" and climaf installed by following the instructions on readthedocs), I have access to CM_atlas, but I can't import it, due to a missing `reference `module

```
(cdatm_py2) [jypmce@ciclad-ng ~]$ wp
/data/jypmce/cdat/miniconda3/envs/cdatm_py2/bin/python

(cdatm_py2) [jypmce@ciclad-ng ~]$ echo $PYTHONPATH
/data/jypmce/cdat/climaf

(cdatm_py2) [jypmce@ciclad-ng ~]$ find /data/jypmce/cdat/climaf -name CM_atlas
/data/jypmce/cdat/climaf/CM_atlas

(cdatm_py2) [jypmce@ciclad-ng ~]$ python
Python 2.7.15 | packaged by conda-forge | (default, Feb 28 2019, 04:00:11)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from CM_atlas import *
Climaf version = 1.2.10
Cache directory set to : /data/jypmce/climaf_cache (use $CLIMAF_CACHE if set)
Cache directory for remote data set to : /data/jypmce/climaf_cache/remote_data (use $CLIMAF_REMOTE_CACHE if set)
Available macros read from ~/.climaf.macros are : []
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/jypmce/cdat/climaf/CM_atlas/__init__.py", line 1, in <module>
    from plot_CM_atlas import *
  File "/data/jypmce/cdat/climaf/CM_atlas/plot_CM_atlas.py", line 3, in <module>
    from reference import variable2reference
ImportError: No module named reference
>>>
```
Any idea what's happening? And a potential quick fix? I'm supposed to produce atlases using climaf before the Barcelona meeting?

**Comment by jypeter** [comment]
After talking to @jservonnat, I have temporarily solved both problems by changing the value of PYTHONPATH from
`/data/jypmce/cdat/climaf`
to
`/home/jservon/C-ESM-EP/restruct/share/cesmep_modules:/data/jypmce/cdat/climaf`

Note that I also had to install `joblib` in my conda, so this is an additional requirement

I'll let you decide if this should be added cleanly to climaf

**Comment by jservonnat** [comment]
CM_atlas will be removed from climaf/1.2.12. The users will have to use CM_atlas from a C-ESM-EP install. I will correct the examples based on CM_atlas.
