### ISSUE TITLE
Have clog add some timestamps to its output?

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#137]
I like to know when my scripts are starting, ending and where they took their time, when I read the scripts' output

I usually print some variation of `time.asctime()`, but I figure this could be achieved automatically by having `clog` prepend some time information to its messages. Probably not for all the `debug` messages, but maybe for “info”, “warning”, “critical”. Or you could specify the timestamp level as a second option of clog, e.g. `clog('debug', timestamp='info')`

**Comment by jservonnat** [comment]
@jypeter we propose to add the date at the beginning and at the end of a cfile command (and the total duration of the command).

**Comment by jservonnat** [comment]
@jypeter would that fit your needs?
```
In [3]: cfile(test)
debug    : cfile called on ds('CMIP6%%tas%1980%global%/bdd%IPSL-CM6A-LR%*%*%Amon%historical%r1i1p1f*%g*%latest')
debug    : Starting cfile at UTC time: 2019-06-17 09:19:19
[...]
debug    : cfile completed at UTC time: 2019-06-17 09:19:49 : total duration = 30.476778s
```

**Comment by jypeter** [comment]
Yes, looks good, but:
- I think I'd rather have the time stamps in local time. Makes it easier to compare it with file dates `(ls -l)`
- if you use local time, you can make the time stamp smaller; e.g. `Starting cfile at: 2019-06-17 09:19:19`
- I almost missed the `s` unit for the duration. If you use a format, can you add a space before it?

**Comment by jservonnat** [comment]
@jypeter first and third points ok. I don't get the second point, isn't it already as you ask?
