### ISSUE TITLE
The available projections are not documented

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#153]
I'd like to know which projections I can use in C-ESM-EP (@jservonnat), and I have not found any obvious reference about that in the climaf documentation (@rigoudyg)

There are some vague references in the examples, but no complete list. I assume you are using NCL parameters, but I don't know NCL and how climaf maps projections to NCL, so trying to find some answers on the NCL website was a failure

- example of a vague reference in C-ESM-EP, in `params_Atmosphere_Surface.py`:
```
# -> Set to a value taken by the argument 'proj' of plot(): GLOB, NH, SH, NH20, SH30...
proj = 'GLOB'
```
- example of a vague reference in the climaf documentation of [plot](https://climaf.readthedocs.io/en/master/scripts/plot.html):
`proj : use it to request a stereopolar projection, as e.g. : “NH”,”SH60”… default: cylindrical equidistant (or native grid, see further below and example Climaf call example).` and then I see some references to `NH40` in the examples, but no explanation of what it means. Searching for `NH40` and `SH60` on the climaf web site did not bring me to a page listing the available projections

**Comment by senesis** [comment]
Yes, the doc for proj should 

- refer to http://www.ncl.ucar.edu/Document/Graphics/Resources/mp.shtml#mpProjection, saying that all values documented there are allowed
- and tell that NH40 stands for northern hemisphere polar stereographic, with a latitude limit of 40°

**Comment by jypeter** [comment]
Thanks @senesis, I'm going to give it a try!

Just to be sure, the allowed values for the `proj=` parameter are either:
- some predefined values/aliases in climaf (`GLOB, NH, SH, NH20, SH30, ...` it would be nice to know all the allowed values, with maybe a link to the source),
- or existing NCL values (`CylindricalEquidistant, Robinson, Mollweide , ...`)

Note that on the _plot page_ (and possibly other places), [some examples use proj as a variable](https://climaf.readthedocs.io/en/master/scripts/plot.html#maps-example), which is a bit misleading, and not very convenient when Searching for _proj_. If somebody wants to correct this, or raise a specific issue about this for later...
```
>>> proj=plot(moy_tas,title='ALADIN',min=-12,max=28,delta=2.5,vcb=False)
>>> cshow(proj)
>>> # How to get required file which includes metadata for the native Lambert grid named 'climaf_plot_grid.nc'
>>> fixed_fields('plot', ('climaf_plot_grid.nc','/cnrm/est/COMMON/climaf/test_data/ALADIN/tas_MED-11_ECMWF-ERAINT_evaluation_r1i1p1_CNRM-ALADIN52_v1_mon_197901-201112.nc'))
>>> # with bringing to the script this file => with default native grid (no re-projection)
>>> cdrop(proj) # to re-compute 'proj'
>>> cshow(proj)
```

**Comment by jypeter** [comment]
I have tried `proj='Robinson'` and it worked fine! See [Atmosphere surface for several midHolocene experiments](https://vesg.ipsl.upmc.fr/thredds/fileServer/IPSLFS/jypmce/C-ESM-EP/PMIP4_0k_ref_jypmce/Atmosphere_Surface_shift/atlas_Atmosphere_Surface_shift_PMIP4_0k_ref.html) (shifted to the [-180, 180] range

Note that _Robinson_ is apparently recommended (required?) for CMIP6 papers, so this projection should definitely be explicitly documented 

It would also be nice to have a border around Robinson plots (#154)
