### ISSUE TITLE
Behaviour of 'TMPDIR does not exist'

### ISSUE THREAD

**Issue by jservonnat** [rigoudyg/climaf#163]
In the branch V1.2.13, if TMPDIR exists as a variable but the directory does not exist, CliMAF returns an error:
```
    if "TMPDIR" in os.environ and not os.path.isdir(os.environ["TMPDIR"]):
       raise OSError("TMPDIR points to a non existing directory! Change the value of the variable to go on.")
```
With the C-ESM-EP, we set TMPDIR automatically as the CLIMAF_CACHE. In case we start fresh, the climaf cache does not necessarily exist.
What do you think about creating the TMPDIR in this case? Like:
```
    if "TMPDIR" in os.environ and not os.path.isdir(os.environ["TMPDIR"]):
        os.makedirs(os.environ["TMPDIR"])
```

**Comment by rigoudyg** [comment]
Changes in code done in V1.2.13.
If the directory does not exists, create it. If the name is not a directory, delete it and then create the directory.
