### ISSUE TITLE
ncdump returns ncdump(object)

### ISSUE THREAD

**Issue by jservonnat** [rigoudyg/climaf#175]
@rigoudyg the ncdump function now only returns the call of the function but not the result of the ncdump command:
```
In [3]: ncdump(dat_cmip5)
Out[3]: ncdump(ds('CMIP5%%tos%1980-2000%global%/bdd%CNRM-CM5%*%historical%r1i1p1%monthly%*%latest'))
```
both in Ipython and Jupyter notebook.
Any idea why it behaves like this now?

**Comment by rigoudyg** [comment]
@jservonnat I did not noticed this issue.
It must be fixed with the commit https://github.com/rigoudyg/climaf/pull/171/commits/099b37fa896693eaabbb427c3dc0ceb3353a73d7 I have just pushed.
Tell me if it does not work

**Comment by jservonnat** [comment]
@rigoudyg it works ;)! thanks!
