### ISSUE TITLE
Mention the "spirit" servers at IPSL

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#243]
The documentation should be updated to mention the new IPSL `spirit` servers, on the pages where `ciclad` is mentioned

The [IPSL Mesocenter documentation](https://documentations.ipsl.fr/MESO_User/) could probably also mention CliMAF and how to initialize it (currently CliMAF only appears in an [example of using module avail](https://documentations.ipsl.fr/MESO_User/Module/Module_command.html))

**Comment by senesis** [comment]
You may use modules in /net/nfs/tools/Users/SU/modulefiles/jservon/climaf/, preferably env20230223_climafV3.e
The CliMAF version is a V3, which has a small backward incompatibility : module climaf.html has been renamed climaf.chtml
The CliMAF doc should definitely be updated, you're right to recall it.

**Comment by senesis** [comment]
Just provide 'module load' with the full path

**Comment by senesis** [comment]
Alternatively, you may add a path to MODULEPATH, using 'module use' :

> use     [-a|-p] dir [...]         Add dir(s) to MODULEPATH variable
> ..
>   -a | --append   Append directory to MODULEPATH (on 'use' sub-command)
>   -p | --prepend  Prepend directory to MODULEPATH
>

**Comment by senesis** [comment]
Here is the copy of a mail dated oct 2022 to climaf.users

> Bonjour
> 
> Les utilisateurs des machines ciclad sont incités à migrer sur spirit. Une version de CliMAF y est validée, et disponible en chargeant un module. La manière recommandée est  de :
>      - configurer son environnement de base (.bashrc) pour qu'il connaisse l'emplacement des modules chargeant CliMAF
> 
>         module use --append /net/nfs/tools/Users/SU/modulefiles/jservon
>
>     - et charger le module correspondant à la version validée pour spirit (qui est basée sur la V 2.0.2)
> 
>          module load climaf/spirit_0
> 
> Un module sera ultérieurement disponible pour utiliser CliMAF V3.0, prochaine version 'officielle' aussi valide sur spirit.
> 
> 
> D'autre part, pour lancer des notebooks utilisant CliMAF, on dispose d'un script approprié (qui charge le module CliMAF ci-dessus) :
> 
>     /net/nfs/tools/Users/SU/jservon/bin/climaf-notebook_spirit_0
> 
> On peut le lancer sur un noeud de calcul par exemple par :
> 
>     srun --pty --mem-per-cpu=9G  --time=60 /net/nfs/tools/Users/SU/jservon/bin/climaf-notebook_spirit_0
> 
> 
> Nota: vous aurez des warnings du type :
> 
>     /bin/bash: /net/nfs/tools/Users/SU/jservon/spirit-2021.11_envs/climaf_spirit_0/lib/libtinfo.so.6: no version information available (required by /bin/bash)
> 
> et
> 
>     Error loading server extension nb_conda
> 
> Il sont sans conséquence.
> 
> 
> Stéphane
